export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_ERROR = 'SET_ERROR';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const LOADING = 'LOADING';
export const SET_BREADCRUMB_ARRAY = 'SET_BREADCRUMB_ARRAY';
export const IS_SEARCH = 'IS_SEARCH';
